name: build


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  ACCOUNT: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}


jobs:

  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
