name: test


# on:
#    workflow_run:
#      workflows: ["build"]
#      types:
#        - completed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
