name: test


on:
   workflow_run:
    workflows: ["build"]
    types:
      - completed
      - success

env:
  ACCOUNT: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}


jobs:

  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
