name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_run:
    workflows: ["build"]
    types:
      - completed


jobs:

  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
